### ISSUE TITLE
Exception when deleting a node (with at least on target)  in the regulatory graph

### ISSUE THREAD

**Issue by chaouiya** [archimede-institut/GINsim#13]
When I deleted a node in a model, I got the expected warning popup window, and when clicking on Yes, the following message appears in the console  (I'm pasting only the first lines). Note that this does not happen when deleting a node with no target.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot read field "l_outgoing" because the return value of "java.util.Map.get(Object)" is null
	at org.ginsim.core.graph.backend.GsJGraphtBaseGraph.outgoingEdgesOf(GsJGraphtBaseGraph.java:252)
	at org.jgrapht.graph.GraphDelegator.outgoingEdgesOf(GraphDelegator.java:282)
	at org.ginsim.core.graph.backend.JgraphtBackendImpl.getOutgoingEdges(JgraphtBackendImpl.java:108)
	at org.ginsim.core.graph.AbstractGraph.getOutgoingEdges(AbstractGraph.java:334)
	at org.ginsim.core.graph.regulatorygraph.RegulatoryGraphImpl.removeEdge(RegulatoryGraphImpl.java:205)
	at org.ginsim.core.graph.regulatorygraph.RegulatoryGraphImpl.removeEdge(RegulatoryGraphImpl.java:30)
	at org.ginsim.gui.graph.DeleteAction.performed(DeleteAction.java:57)

**Comment by chaouiya** [comment]
I just tested and I'm still getting aan exception 
java.lang.NullPointerException: Cannot read field "l_incoming" because the return value of "java.util.Map.get(Object)" is null
	at org.ginsim.core.graph.backend.GsJGraphtBaseGraph.incomingEdgesOf(GsJGraphtBaseGraph.java:238)
	at org.jgrapht.graph.GraphDelegator.incomingEdgesOf(GraphDelegator.java:264)
	at org.ginsim.core.graph.backend.JgraphtBackendImpl.getIncomingEdges(JgraphtBackendImpl.java:104)
	at org.ginsim.core.graph.AbstractGraph.getIncomingEdges(AbstractGraph.java:329)
