### ISSUE TITLE
Exception launched when deleting a component (updated)

### ISSUE THREAD

**Issue by chaouiya** [archimede-institut/GINsim#18]
Already described in a Issue #13, please check the comment that follows
 When deleting a component e.g.  deleting G2 where G1-->G2
if the behaviour of G2 is defined through a function (and not a parameter), the component is delete but the following  exceptions are launched (only first ones reported here)
java.lang.NullPointerException: Cannot read field "l_incoming" because the return value of "java.util.Map.get(Object)" is null
	at org.ginsim.core.graph.backend.GsJGraphtBaseGraph.incomingEdgesOf(GsJGraphtBaseGraph.java:238)
	at org.jgrapht.graph.GraphDelegator.incomingEdgesOf(GraphDelegator.java:264)
	at org.ginsim.core.graph.backend.JgraphtBackendImpl.getIncomingEdges(JgraphtBackendImpl.java:104)
	at org.ginsim.core.graph.AbstractGraph.getIncomingEdges(AbstractGraph.java:329)

**Comment by chaouiya** [comment]
worse... today I got another problem related to the definition of parameters (this was not possible anymore after a deletion of some components).... still need to characterize this bug, but it's a serious one ;-(

**Comment by chaouiya** [comment]
This bug exists in GINsim-3.0.0b-SNAPSHOT-jar-with-dependencies.jar

**Comment by chaouiya** [comment]
Seems to be related to the previous comments, i.e. node deletion is not correctly done.

For an input node, i.e. a node with no regulator, it is possible to either
1)  check the "Input" checkbox, which means that the node remains at a constant value 0, or 1 
2) define a basal value for this node 0 (this is the default) or 1. To do so, in the parameter view, it is enough to clik on the green arrow without selecting any interaction (in fact there is none).

This second option does not work in the current GINsim working version when turing a node into an input by deleting its regulator. Here is the exception which is launched
java -jar target/GINsim-3.0.0b-SNAPSHOT.jar
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at org.ginsim.gui.graph.regulatorygraph.InteractionPanel.insertRight2Left(InteractionPanel.java:473)
	at org.ginsim.gui.graph.regulatorygraph.InteractionPanel$3.actionPerformed(InteractionPanel.java:307)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)

**Comment by dbenielli** [comment]
The bug is fixed but some aspects remain misunderstood:

1. First ERROR:

> +++ b/src/main/java/org/ginsim/core/graph/backend/GsJGraphtBaseGraph.java
>  Set<E> l = m_vertices.get(vertex).l_outgoing;
>   m_vertices.get(vertex) can by null


2. Second ERROR:

      - not necessary for tis fix

```
+++ b/src/main/java/org/ginsim/core/graph/backend/JgraphtBackendImpl.java
+       @Override
+       public void updateEvsmap(){
Add function updateEvsmap to remove removed edge in evsmap attribut,  Bug  Issue #18 remove in evsmap removed Edge (but not related with bug)
```

   - not related to this fix should  be remove

```
+++b/src/main/java/org/ginsim/gui/graph/hierarchicaltransitiongraph/HierarchicalTableModel.java
 extra content stuff related to enhansment should be remove
 
 // lot of stuff for extraContent but not working correctly should be remove
```


  - fix itself (stil some ?)

```
+++ b/src/main/java/org/ginsim/gui/graph/regulatorygraph/InteractionPanel.java


// Bug issue #18 
				if (objs != null && i < objs.length && objs[i] != null) 
```

fix the bug but the different behaviour with and without previous deleting action is not understanding



-  Fix in 

```
 $ git push fork main
Énumération des objets: 68, fait.
Décompte des objets: 100% (68/68), fait.
Compression par delta en utilisant jusqu'à 12 fils d'exécution
Compression des objets: 100% (35/35), fait.
Écriture des objets: 100% (36/36), 5.76 Kio | 1.44 Mio/s, fait.
Total 36 (delta 27), réutilisés 0 (delta 0), réutilisés du pack 0
remote: Resolving deltas: 100% (27/27), completed with 27 local objects.
To github.com:archimede-institut/GINsim.git
   81543795..4879c51a  main -> main
```
